version: '3'
services:
  nuxt:
    build:
      context: ./docker/nuxtjs
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./container/front/nuxtjs:/var/www/nuxtjs
    working_dir: "/var/www/nuxtjs"
    command: yarn dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      learning-network:
        ipv4_address: 172.16.0.100
  
  laravel:
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    ports:
      - 127.0.0.100:80:80
    volumes:
      - ./container/backend/laravel:/var/www/laravel-test
      - ./container/backend/laravel:/var/www/laravel-prod
      - ./docker/laravel/000-default.conf:/etc/apache2/sites-enabled/000-default.conf

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf 
      # - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.200:3306:3306
      

networks:
  learning-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16